-- GlobalStore: normalized name + slug auto flag
ALTER TABLE "GlobalStore" ADD COLUMN "normalizedName" TEXT;
ALTER TABLE "GlobalStore" ADD COLUMN "slugAutoGenerated" BOOLEAN NOT NULL DEFAULT true;

UPDATE "GlobalStore"
SET "normalizedName" = lower(trim(regexp_replace(
  translate(
    "name",
    'İIıŞşĞğÜüÖöÇç',
    'iiisssgguuuooocc'
  ),
  '\s+', ' ', 'g'
)))
WHERE "normalizedName" IS NULL;

UPDATE "GlobalStore"
SET "normalizedName" = "id"
WHERE "normalizedName" IS NULL OR "normalizedName" = '';

-- Resolve duplicate normalized names (e.g. legacy seed data) before unique index
WITH ranked AS (
  SELECT
    id,
    "normalizedName",
    ROW_NUMBER() OVER (
      PARTITION BY "normalizedName"
      ORDER BY ("deletedAt" IS NULL) DESC, "createdAt" ASC, id ASC
    ) AS rn
  FROM "GlobalStore"
)
UPDATE "GlobalStore" g
SET "normalizedName" = g."normalizedName" || '-' || r.rn
FROM ranked r
WHERE g.id = r.id
  AND r.rn > 1;

ALTER TABLE "GlobalStore" ALTER COLUMN "normalizedName" SET NOT NULL;
CREATE UNIQUE INDEX "GlobalStore_normalizedName_key" ON "GlobalStore"("normalizedName");

-- MallStore: rename localName -> displayTitle, add phones + floor FK
ALTER TABLE "MallStore" RENAME COLUMN "localName" TO "displayTitle";
ALTER TABLE "MallStore" ADD COLUMN "whatsappPhone" TEXT;
ALTER TABLE "MallStore" ADD COLUMN "floorId" TEXT;

-- MallFloor
CREATE TABLE "MallFloor" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "mallId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MallFloor_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "MallFloor_mallId_name_key" ON "MallFloor"("mallId", "name");
CREATE INDEX "MallFloor_tenantId_mallId_active_idx" ON "MallFloor"("tenantId", "mallId", "active");
CREATE INDEX "MallFloor_mallId_sortOrder_idx" ON "MallFloor"("mallId", "sortOrder");

ALTER TABLE "MallFloor" ADD CONSTRAINT "MallFloor_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MallFloor" ADD CONSTRAINT "MallFloor_mallId_fkey" FOREIGN KEY ("mallId") REFERENCES "Mall"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Migrate distinct floor strings into MallFloor (per mall)
INSERT INTO "MallFloor" ("id", "tenantId", "mallId", "name", "label", "sortOrder", "active", "createdAt", "updatedAt")
SELECT
  'mf_' || substr(md5("mallId" || ':' || trim("floor")), 1, 24),
  "tenantId",
  "mallId",
  trim("floor"),
  trim("floor"),
  row_number() OVER (PARTITION BY "mallId" ORDER BY trim("floor")) - 1,
  true,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
FROM "MallStore"
WHERE "floor" IS NOT NULL AND trim("floor") <> '' AND "deletedAt" IS NULL
GROUP BY "tenantId", "mallId", trim("floor");

UPDATE "MallStore" ms
SET "floorId" = mf."id"
FROM "MallFloor" mf
WHERE ms."mallId" = mf."mallId"
  AND ms."floor" IS NOT NULL
  AND trim(ms."floor") = mf."name"
  AND ms."deletedAt" IS NULL;

CREATE INDEX "MallStore_floorId_idx" ON "MallStore"("floorId");
ALTER TABLE "MallStore" ADD CONSTRAINT "MallStore_floorId_fkey" FOREIGN KEY ("floorId") REFERENCES "MallFloor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
