export type NavItem = {
  id: string;
  label: string;
  icon: string;
  href: string;
  permission: string | null;
  /** User must hold at least one of these (OR). Overrides `permission` when set. */
  anyPermission?: string[];
  /** If set, the tenant must have this capability enabled for the item to appear. */
  capability?: string;
  /** If true, only Super Admins see this item (no tenant context needed). */
  superAdminOnly?: boolean;
  /** Hide when audit logging is disabled (AUDIT_ENABLED / VITE_AUDIT_ENABLED). */
  requiresAudit?: boolean;
  group?: string;
  /** Optional nested section label within a group (e.g. Lokalizasyon under Sistem). */
  subgroup?: string;
};

export const NAV_ITEMS: NavItem[] = [
  {
    id: 'dashboard',
    label: 'Gösterge Paneli',
    icon: '◉',
    href: '/dashboard',
    permission: null,
  },
  {
    id: 'notifications',
    label: 'Bildirimler',
    icon: '✦',
    href: '/notifications',
    permission: 'notification:read',
    capability: 'notifications',
  },
  {
    id: 'search',
    label: 'Genel Arama',
    icon: '⌕',
    href: '/search',
    permission: 'search:global',
    capability: 'search',
  },
  {
    id: 'media',
    label: 'Medya Kütüphanesi',
    icon: '▤',
    href: '/media',
    permission: 'media:read',
    capability: 'media',
  },
  {
    id: 'media-guidelines',
    label: 'Medya Boyut Ayarları',
    icon: '▥',
    href: '/media/guidelines',
    permission: 'media:read',
    capability: 'media',
    group: 'Ayarlar',
  },
  {
    id: 'sliders',
    label: 'Slider Yönetimi',
    icon: '▦',
    href: '/sliders',
    permission: 'slider:read',
    capability: 'sliders',
  },
  {
    id: 'analytics',
    label: 'Raporlar',
    icon: '∑',
    href: '/analytics',
    permission: 'analytics:view',
    capability: 'analytics',
    group: 'Analitik',
  },
  {
    id: 'events',
    label: 'Etkinlikler',
    icon: '◷',
    href: '/events',
    permission: 'event:read',
    capability: 'events',
    group: 'İçerik',
  },
  {
    id: 'campaigns',
    label: 'Kampanyalar',
    icon: '◈',
    href: '/campaigns',
    permission: 'campaign:read',
    capability: 'campaigns',
    group: 'İçerik',
  },
  {
    id: 'popups',
    label: 'Popuplar',
    icon: '◆',
    href: '/popups',
    permission: 'popup:read',
    capability: 'popups',
    group: 'İçerik',
  },
  {
    id: 'pages',
    label: 'Sayfalar',
    icon: '◧',
    href: '/pages',
    permission: 'page:read',
    capability: 'pages',
    group: 'İçerik',
  },
  {
    id: 'movies',
    label: 'Filmler',
    icon: '◐',
    href: '/movies',
    permission: 'movie:read',
    capability: 'cinema',
    group: 'İçerik',
    subgroup: 'Filmler',
  },
  {
    id: 'movie-categories',
    label: 'Film Kategorileri',
    icon: '◑',
    href: '/movie-categories',
    permission: 'movie:read',
    capability: 'cinema',
    group: 'İçerik',
    subgroup: 'Filmler',
  },
  {
    id: 'tmdb-hub',
    label: 'TMDB Merkezi',
    icon: '◎',
    href: '/tmdb-hub',
    permission: 'movie:read',
    capability: 'cinema',
    group: 'İçerik',
    subgroup: 'Filmler',
  },
  {
    id: 'global-stores',
    label: 'Global Mağazalar',
    icon: '▣',
    href: '/global-stores',
    permission: 'global-store:read',
    capability: 'stores',
    group: 'Lokasyon',
  },
  {
    id: 'mall-stores',
    label: 'AVM Mağazaları',
    icon: '▩',
    href: '/mall-stores',
    permission: 'mall-store:read',
    capability: 'stores',
    group: 'Lokasyon',
  },
  {
    id: 'store-categories',
    label: 'Mağaza Kategorileri',
    icon: '▧',
    href: '/store-categories',
    permission: 'store-category:read',
    capability: 'stores',
    group: 'Lokasyon',
  },
  {
    id: 'floors',
    label: 'Katlar',
    icon: '▥',
    href: '/floors',
    permission: null,
    anyPermission: ['location:read', 'mall-store:read'],
    capability: 'stores',
    group: 'Lokasyon',
  },
  {
    id: 'services',
    label: 'Hizmetler',
    icon: '◇',
    href: '/services',
    permission: 'service:read',
    capability: 'location_services',
    group: 'Lokasyon',
  },
  {
    id: 'cinemas',
    label: 'Sinemalar',
    icon: '▶',
    href: '/cinemas',
    permission: 'cinema:read',
    capability: 'cinema',
    group: 'Lokasyon',
  },
  {
    id: 'restaurants',
    label: 'Restoranlar',
    icon: '◔',
    href: '/restaurants',
    permission: 'location:read',
    capability: 'stores',
    group: 'Lokasyon',
  },
  {
    id: 'tenants',
    label: 'Müşteriler',
    icon: '◑',
    href: '/tenants',
    permission: 'tenant:read',
    superAdminOnly: true,
    group: 'Sistem',
  },
  {
    id: 'system-languages',
    label: 'Sistem Dilleri',
    icon: '◌',
    href: '/system/localization/languages',
    permission: 'system-language:read',
    capability: 'localization',
    superAdminOnly: true,
    group: 'Sistem',
    subgroup: 'Lokalizasyon',
  },
  {
    id: 'capabilities',
    label: 'Lisanslar',
    icon: '◎',
    href: '/capabilities',
    permission: 'capability:read',
    superAdminOnly: true,
    group: 'Sistem',
  },
  {
    id: 'audit-logs',
    label: 'Denetim Günlükleri',
    icon: '◫',
    href: '/audit-logs',
    permission: 'audit:read',
    requiresAudit: true,
    group: 'Sistem',
  },
  {
    id: 'locations',
    label: 'Lokasyonlar',
    icon: '◈',
    href: '/locations',
    permission: 'location:read',
    group: 'Yönetim',
  },
  {
    id: 'users',
    label: 'Kullanıcılar',
    icon: '◉',
    href: '/users',
    permission: 'user:read',
    group: 'Yönetim',
  },
  {
    id: 'roles',
    label: 'Roller',
    icon: '◧',
    href: '/roles',
    permission: 'role:read',
    group: 'Yönetim',
  },
  {
    id: 'settings-general',
    label: 'Genel Ayarlar',
    icon: '◧',
    href: '/settings/general',
    permission: 'settings:read',
    group: 'Ayarlar',
  },
  {
    id: 'settings-movie-providers',
    label: 'Film Sağlayıcıları',
    icon: '◎',
    href: '/settings/movie-providers',
    permission: 'settings:read',
    capability: 'cinema',
    group: 'Ayarlar',
  },
  {
    id: 'settings-security',
    label: 'Güvenlik',
    icon: '◫',
    href: '/settings/security',
    permission: 'settings:read',
    group: 'Ayarlar',
  },
  {
    id: 'settings-developer-api',
    label: 'Developer API',
    icon: '⌗',
    href: '/settings/developer-api',
    permission: 'settings:read',
    group: 'Ayarlar',
  },
  {
    id: 'settings-languages',
    label: 'Diller',
    icon: '◌',
    href: '/settings/languages',
    permission: 'location:read',
    capability: 'localization',
    group: 'Ayarlar',
  },
  {
    id: 'account',
    label: 'Hesabım',
    icon: '◌',
    href: '/account',
    permission: null,
    group: 'Ayarlar',
  },
];

export const NAV_GROUPS = ['Analitik', 'İçerik', 'Lokasyon', 'Sistem', 'Yönetim', 'Ayarlar'] as const;
