-- MallStore: single category FK
ALTER TABLE "MallStore" ADD COLUMN IF NOT EXISTS "categoryId" TEXT;

-- StoreCategory: mall-scoped refactor (add columns before data migration)
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "tenantId" TEXT;
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "mallId" TEXT;
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "parentCategoryId" TEXT;
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "normalizedName" TEXT;
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "slugAutoGenerated" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "active" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "color" TEXT;
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "showInWebsite" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "showInMobile" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "showInKiosk" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "seoDescription" TEXT;
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "sameImageForAllLocales" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "iconMediaId" TEXT;
ALTER TABLE "StoreCategory" ADD COLUMN IF NOT EXISTS "coverMediaId" TEXT;

-- Allow duplicate slugs across legacy rows while copying per mall
DROP INDEX IF EXISTS "StoreCategory_slug_key";

-- Duplicate legacy global categories per mall
CREATE TEMP TABLE "_StoreCategoryMallMap" (
  "legacyId" TEXT NOT NULL,
  "mallId" TEXT NOT NULL,
  "newId" TEXT NOT NULL,
  PRIMARY KEY ("legacyId", "mallId")
);

INSERT INTO "_StoreCategoryMallMap" ("legacyId", "mallId", "newId")
SELECT
  sc.id,
  m.id,
  'sc_' || substr(md5(sc.id || ':' || m.id), 1, 24)
FROM "StoreCategory" sc
CROSS JOIN "Mall" m
WHERE sc."tenantId" IS NULL AND sc."deletedAt" IS NULL;

INSERT INTO "StoreCategory" (
  id, "tenantId", "mallId", name, description, "normalizedName", slug, "slugAutoGenerated",
  "sortOrder", active, "iconMediaId", "createdAt", "updatedAt", "deletedAt"
)
SELECT
  map."newId",
  m."tenantId",
  m.id,
  sc.name,
  NULL,
  lower(trim(regexp_replace(translate(sc.name, 'İIıŞşĞğÜüÖöÇç', 'iiisssgguuuooocc'), '\s+', ' ', 'g'))),
  sc.slug || '-' || substr(md5(m.id || ':' || sc.id), 1, 8),
  true,
  sc."sortOrder",
  CASE WHEN sc.status = 'ACTIVE' THEN true ELSE false END,
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP,
  sc."deletedAt"
FROM "_StoreCategoryMallMap" map
JOIN "StoreCategory" sc ON sc.id = map."legacyId"
JOIN "Mall" m ON m.id = map."mallId"
WHERE NOT EXISTS (SELECT 1 FROM "StoreCategory" existing WHERE existing.id = map."newId");

-- Assign mall store category from first junction link
UPDATE "MallStore" ms
SET "categoryId" = map."newId"
FROM "MallStoreOnCategory" moc
JOIN "_StoreCategoryMallMap" map ON map."legacyId" = moc."storeCategoryId"
WHERE ms.id = moc."mallStoreId"
  AND map."mallId" = ms."mallId"
  AND ms."categoryId" IS NULL;

-- Remove legacy global categories
DELETE FROM "StoreCategory" WHERE "tenantId" IS NULL;

-- Drop legacy columns / constraints
DROP INDEX IF EXISTS "StoreCategory_slug_key";
ALTER TABLE "StoreCategory" DROP COLUMN IF EXISTS "icon";
ALTER TABLE "StoreCategory" DROP COLUMN IF EXISTS "status";

ALTER TABLE "GlobalStore" DROP CONSTRAINT IF EXISTS "GlobalStore_categoryId_fkey";
ALTER TABLE "GlobalStore" DROP COLUMN IF EXISTS "categoryId";

DROP TABLE IF EXISTS "MallStoreOnCategory";

-- Resolve duplicate normalized names per mall
WITH ranked AS (
  SELECT
    id,
    "normalizedName",
    "mallId",
    ROW_NUMBER() OVER (
      PARTITION BY "mallId", "normalizedName"
      ORDER BY ("deletedAt" IS NULL) DESC, "createdAt" ASC, id ASC
    ) AS rn
  FROM "StoreCategory"
  WHERE "mallId" IS NOT NULL
)
UPDATE "StoreCategory" sc
SET "normalizedName" = sc."normalizedName" || '-' || r.rn
FROM ranked r
WHERE sc.id = r.id AND r.rn > 1;

ALTER TABLE "StoreCategory" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "StoreCategory" ALTER COLUMN "mallId" SET NOT NULL;
ALTER TABLE "StoreCategory" ALTER COLUMN "normalizedName" SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "StoreCategory_mallId_slug_key" ON "StoreCategory"("mallId", slug);
CREATE UNIQUE INDEX IF NOT EXISTS "StoreCategory_mallId_normalizedName_key" ON "StoreCategory"("mallId", "normalizedName");
CREATE INDEX IF NOT EXISTS "StoreCategory_tenantId_mallId_active_idx" ON "StoreCategory"("tenantId", "mallId", active);
CREATE INDEX IF NOT EXISTS "StoreCategory_parentCategoryId_idx" ON "StoreCategory"("parentCategoryId");
CREATE INDEX IF NOT EXISTS "StoreCategory_mallId_sortOrder_idx" ON "StoreCategory"("mallId", "sortOrder");

DO $$ BEGIN
  ALTER TABLE "StoreCategory" ADD CONSTRAINT "StoreCategory_tenantId_fkey"
    FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "StoreCategory" ADD CONSTRAINT "StoreCategory_mallId_fkey"
    FOREIGN KEY ("mallId") REFERENCES "Mall"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "StoreCategory" ADD CONSTRAINT "StoreCategory_parentCategoryId_fkey"
    FOREIGN KEY ("parentCategoryId") REFERENCES "StoreCategory"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "StoreCategory" ADD CONSTRAINT "StoreCategory_iconMediaId_fkey"
    FOREIGN KEY ("iconMediaId") REFERENCES "MediaAsset"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "StoreCategory" ADD CONSTRAINT "StoreCategory_coverMediaId_fkey"
    FOREIGN KEY ("coverMediaId") REFERENCES "MediaAsset"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "StoreCategoryTranslation" (
  id TEXT NOT NULL,
  "storeCategoryId" TEXT NOT NULL,
  "localeId" TEXT NOT NULL,
  "iconMediaId" TEXT,
  "coverMediaId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "StoreCategoryTranslation_pkey" PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS "StoreCategoryTranslation_storeCategoryId_localeId_key"
  ON "StoreCategoryTranslation"("storeCategoryId", "localeId");
CREATE INDEX IF NOT EXISTS "StoreCategoryTranslation_localeId_idx" ON "StoreCategoryTranslation"("localeId");

DO $$ BEGIN
  ALTER TABLE "StoreCategoryTranslation" ADD CONSTRAINT "StoreCategoryTranslation_storeCategoryId_fkey"
    FOREIGN KEY ("storeCategoryId") REFERENCES "StoreCategory"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "StoreCategoryTranslation" ADD CONSTRAINT "StoreCategoryTranslation_localeId_fkey"
    FOREIGN KEY ("localeId") REFERENCES "Locale"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "StoreCategoryTranslation" ADD CONSTRAINT "StoreCategoryTranslation_iconMediaId_fkey"
    FOREIGN KEY ("iconMediaId") REFERENCES "MediaAsset"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "StoreCategoryTranslation" ADD CONSTRAINT "StoreCategoryTranslation_coverMediaId_fkey"
    FOREIGN KEY ("coverMediaId") REFERENCES "MediaAsset"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "MallStore_categoryId_idx" ON "MallStore"("categoryId");

DO $$ BEGIN
  ALTER TABLE "MallStore" ADD CONSTRAINT "MallStore_categoryId_fkey"
    FOREIGN KEY ("categoryId") REFERENCES "StoreCategory"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- LocalizedEntityType: STORE_CATEGORY
ALTER TYPE "LocalizedEntityType" ADD VALUE IF NOT EXISTS 'STORE_CATEGORY';

DROP TYPE IF EXISTS "StoreCategoryStatus";
