/**
 * URL-safe slug from display name (ASCII fallback for non-latin chars).
 */
export function slugify(input: string): string {
  const base = input
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return base.length > 0 ? base : 'item';
}

/** Slug was auto-generated from title (including uniqueness suffixes like -1, -2). */
export function isAutoGeneratedContentSlug(slug: string, title: string): boolean {
  const base = slugify(title);
  if (slug === base) return true;
  if (!slug.startsWith(`${base}-`)) return false;
  const suffix = slug.slice(base.length + 1);
  return /^\d+$/.test(suffix) && Number(suffix) >= 1;
}

export function resolveUseCustomSlug(slug: string, title: string): boolean {
  return !isAutoGeneratedContentSlug(slug, title);
}

export function contentSlugForPayload(opts: {
  useCustomSlug: boolean;
  slug: string;
}): string | undefined {
  if (!opts.useCustomSlug) return undefined;
  const trimmed = opts.slug.trim();
  return trimmed || undefined;
}
