/** OpenAPI tag translation keys — use with @ApiTags(). */
export const SWAGGER_TAGS = {
  AUTH: 'tags.authentication',
  USERS: 'tags.users',
  ROLES: 'tags.roles',
  PERMISSIONS: 'tags.permissions',
  TENANTS: 'tags.tenants',
  SYSTEM_TENANTS: 'tags.systemTenants',
  MALLS: 'tags.malls',
  MEDIA: 'tags.media',
  CAMPAIGNS: 'tags.campaigns',
  EVENTS: 'tags.events',
  STORES: 'tags.stores',
  GLOBAL_STORES: 'tags.global.stores',
  PAGES: 'tags.pages',
  SLIDERS: 'tags.sliders',
  SLIDER_GROUPS: 'tags.slider.groups',
  POPUPS: 'tags.popups',
  SERVICES: 'tags.services',
  MOVIES: 'tags.movies',
  MOVIE_PROVIDERS: 'tags.movieProviders',
  RESTAURANTS: 'tags.restaurants',
  DASHBOARD: 'tags.dashboard',
  SETTINGS: 'tags.settings',
  SEARCH: 'tags.search',
  PUBLIC: 'tags.public.api',
  PUBLIC_HOMEPAGE: 'tags.public.homepage',
  PUBLIC_SITE_CONFIG: 'tags.public.siteConfig',
  PUBLIC_SLIDERS: 'tags.public.sliders',
  PUBLIC_CAMPAIGNS: 'tags.public.campaigns',
  PUBLIC_EVENTS: 'tags.public.events',
  PUBLIC_STORES: 'tags.public.stores',
  PUBLIC_PAGES: 'tags.public.pages',
  PUBLIC_SERVICES: 'tags.public.services',
  PUBLIC_MOVIES: 'tags.public.movies',
  PUBLIC_SEARCH: 'tags.public.search',
  PUBLIC_POPUPS: 'tags.public.popups',
  PUBLIC_MEDIA_GUIDELINES: 'tags.public.mediaGuidelines',
  HEALTH: 'tags.health',
  VERSION: 'tags.version',
  AUDIT: 'tags.audit',
  ANALYTICS: 'tags.analytics',
  NOTIFICATIONS: 'tags.notifications',
  TRANSLATIONS: 'tags.translations',
  LOCALES: 'tags.locales',
  SYSTEM_LOCALES: 'tags.systemLocales',
  CAPABILITIES: 'tags.capabilities',
  CINEMAS: 'tags.cinemas',
  MOVIE_SESSIONS: 'tags.movie.sessions',
  STORE_CATEGORIES: 'tags.store.categories',
  PAGE_BLOCKS: 'tags.page.blocks',
  DEVELOPER_API: 'tags.developer.api',
} as const;

export const TAG_DESCRIPTION_KEYS: Record<string, string> = {
  [SWAGGER_TAGS.AUTH]: 'tags.authentication.description',
  [SWAGGER_TAGS.USERS]: 'tags.users.description',
  [SWAGGER_TAGS.ROLES]: 'tags.roles.description',
  [SWAGGER_TAGS.PERMISSIONS]: 'tags.permissions.description',
  [SWAGGER_TAGS.TENANTS]: 'tags.tenants.description',
  [SWAGGER_TAGS.SYSTEM_TENANTS]: 'tags.systemTenants.description',
  [SWAGGER_TAGS.MALLS]: 'tags.malls.description',
  [SWAGGER_TAGS.MEDIA]: 'tags.media.description',
  [SWAGGER_TAGS.CAMPAIGNS]: 'tags.campaigns.description',
  [SWAGGER_TAGS.EVENTS]: 'tags.events.description',
  [SWAGGER_TAGS.STORES]: 'tags.stores.description',
  [SWAGGER_TAGS.GLOBAL_STORES]: 'tags.global.stores.description',
  [SWAGGER_TAGS.PAGES]: 'tags.pages.description',
  [SWAGGER_TAGS.SLIDERS]: 'tags.sliders.description',
  [SWAGGER_TAGS.SLIDER_GROUPS]: 'tags.slider.groups.description',
  [SWAGGER_TAGS.POPUPS]: 'tags.popups.description',
  [SWAGGER_TAGS.SERVICES]: 'tags.services.description',
  [SWAGGER_TAGS.MOVIES]: 'tags.movies.description',
  [SWAGGER_TAGS.MOVIE_PROVIDERS]: 'tags.movieProviders.description',
  [SWAGGER_TAGS.RESTAURANTS]: 'tags.restaurants.description',
  [SWAGGER_TAGS.DASHBOARD]: 'tags.dashboard.description',
  [SWAGGER_TAGS.SETTINGS]: 'tags.settings.description',
  [SWAGGER_TAGS.SEARCH]: 'tags.search.description',
  [SWAGGER_TAGS.PUBLIC]: 'tags.public.api.description',
  [SWAGGER_TAGS.PUBLIC_HOMEPAGE]: 'tags.public.homepage.description',
  [SWAGGER_TAGS.PUBLIC_SITE_CONFIG]: 'tags.public.siteConfig.description',
  [SWAGGER_TAGS.PUBLIC_SLIDERS]: 'tags.public.sliders.description',
  [SWAGGER_TAGS.PUBLIC_CAMPAIGNS]: 'tags.public.campaigns.description',
  [SWAGGER_TAGS.PUBLIC_EVENTS]: 'tags.public.events.description',
  [SWAGGER_TAGS.PUBLIC_STORES]: 'tags.public.stores.description',
  [SWAGGER_TAGS.PUBLIC_PAGES]: 'tags.public.pages.description',
  [SWAGGER_TAGS.PUBLIC_SERVICES]: 'tags.public.services.description',
  [SWAGGER_TAGS.PUBLIC_MOVIES]: 'tags.public.movies.description',
  [SWAGGER_TAGS.PUBLIC_SEARCH]: 'tags.public.search.description',
  [SWAGGER_TAGS.PUBLIC_POPUPS]: 'tags.public.popups.description',
  [SWAGGER_TAGS.PUBLIC_MEDIA_GUIDELINES]: 'tags.public.mediaGuidelines.description',
  [SWAGGER_TAGS.HEALTH]: 'tags.health.description',
  [SWAGGER_TAGS.VERSION]: 'tags.version.description',
  [SWAGGER_TAGS.AUDIT]: 'tags.audit.description',
  [SWAGGER_TAGS.ANALYTICS]: 'tags.analytics.description',
  [SWAGGER_TAGS.NOTIFICATIONS]: 'tags.notifications.description',
  [SWAGGER_TAGS.TRANSLATIONS]: 'tags.translations.description',
  [SWAGGER_TAGS.LOCALES]: 'tags.locales.description',
  [SWAGGER_TAGS.SYSTEM_LOCALES]: 'tags.systemLocales.description',
  [SWAGGER_TAGS.CAPABILITIES]: 'tags.capabilities.description',
  [SWAGGER_TAGS.CINEMAS]: 'tags.cinemas.description',
  [SWAGGER_TAGS.MOVIE_SESSIONS]: 'tags.movie.sessions.description',
  [SWAGGER_TAGS.STORE_CATEGORIES]: 'tags.store.categories.description',
  [SWAGGER_TAGS.PAGE_BLOCKS]: 'tags.page.blocks.description',
  [SWAGGER_TAGS.DEVELOPER_API]: 'tags.developer.api.description',
};

export const OPENAPI_TAG_GROUPS = [
  {
    nameKey: 'tagGroup.gettingStarted.name',
    tags: [SWAGGER_TAGS.PUBLIC, SWAGGER_TAGS.AUTH, SWAGGER_TAGS.HEALTH, SWAGGER_TAGS.VERSION],
  },
  {
    nameKey: 'tagGroup.identityAccess.name',
    tags: [
      SWAGGER_TAGS.AUTH,
      SWAGGER_TAGS.USERS,
      SWAGGER_TAGS.ROLES,
      SWAGGER_TAGS.PERMISSIONS,
      SWAGGER_TAGS.CAPABILITIES,
    ],
  },
  {
    nameKey: 'tagGroup.organization.name',
    tags: [SWAGGER_TAGS.TENANTS, SWAGGER_TAGS.SYSTEM_TENANTS, SWAGGER_TAGS.MALLS, SWAGGER_TAGS.SETTINGS, SWAGGER_TAGS.SYSTEM_LOCALES, SWAGGER_TAGS.LOCALES],
  },
  {
    nameKey: 'tagGroup.content.name',
    tags: [
      SWAGGER_TAGS.CAMPAIGNS,
      SWAGGER_TAGS.EVENTS,
      SWAGGER_TAGS.PAGES,
      SWAGGER_TAGS.PAGE_BLOCKS,
      SWAGGER_TAGS.POPUPS,
      SWAGGER_TAGS.SLIDERS,
      SWAGGER_TAGS.MEDIA,
    ],
  },
  {
    nameKey: 'tagGroup.commerce.name',
    tags: [
      SWAGGER_TAGS.STORES,
      SWAGGER_TAGS.GLOBAL_STORES,
      SWAGGER_TAGS.STORE_CATEGORIES,
      SWAGGER_TAGS.SERVICES,
      SWAGGER_TAGS.CINEMAS,
      SWAGGER_TAGS.MOVIES,
      SWAGGER_TAGS.MOVIE_PROVIDERS,
      SWAGGER_TAGS.MOVIE_SESSIONS,
    ],
  },
  {
    nameKey: 'tagGroup.operations.name',
    tags: [
      SWAGGER_TAGS.DASHBOARD,
      SWAGGER_TAGS.SEARCH,
      SWAGGER_TAGS.AUDIT,
      SWAGGER_TAGS.ANALYTICS,
      SWAGGER_TAGS.NOTIFICATIONS,
      SWAGGER_TAGS.TRANSLATIONS,
    ],
  },
  {
    nameKey: 'tagGroup.developerApi.name',
    tags: [SWAGGER_TAGS.DEVELOPER_API],
  },
];

/** Scalar sidebar groups for /developer (frontend integration API only). */
export const DEVELOPER_PORTAL_TAG_GROUPS = [
  {
    nameKey: 'tagGroup.developer.content.name',
    tags: [
      SWAGGER_TAGS.PUBLIC_HOMEPAGE,
      SWAGGER_TAGS.PUBLIC_SITE_CONFIG,
      SWAGGER_TAGS.PUBLIC_SLIDERS,
      SWAGGER_TAGS.PUBLIC_CAMPAIGNS,
      SWAGGER_TAGS.PUBLIC_EVENTS,
      SWAGGER_TAGS.PUBLIC_STORES,
      SWAGGER_TAGS.PUBLIC_PAGES,
      SWAGGER_TAGS.PUBLIC_SERVICES,
      SWAGGER_TAGS.PUBLIC_MOVIES,
      SWAGGER_TAGS.PUBLIC_SEARCH,
      SWAGGER_TAGS.PUBLIC_POPUPS,
      SWAGGER_TAGS.PUBLIC_MEDIA_GUIDELINES,
    ],
  },
];

/** Short API summary for main OpenAPI info.description (Scalar Introduction). */
export const API_INTRO_KEY = 'intro.summary';

/** @deprecated Use API_INTRO_KEY — large intro lives in gettingStarted.markdown */
export const API_INTRO_MARKDOWN = API_INTRO_KEY;

export const GETTING_STARTED_TITLE_KEY = 'gettingStarted.title';
export const RECIPES_TITLE_KEY = 'recipes.title';

export const TAG_DESCRIPTIONS = TAG_DESCRIPTION_KEYS;
