import { appendLimitParam } from './constants';
import { request } from './client';

export type StoreStatus = 'ACTIVE' | 'PASSIVE' | 'ARCHIVED';

export type StoreCategoryMediaPreview = {
  id: string;
  publicUrl: string;
  originalName: string;
  mimeType: string;
};

export type StoreCategory = {
  id: string;
  tenantId: string;
  mallId: string;
  parentCategoryId: string | null;
  name: string;
  description: string | null;
  slug: string;
  slugAutoGenerated: boolean;
  sortOrder: number;
  active: boolean;
  color: string | null;
  showInWebsite: boolean;
  showInMobile: boolean;
  showInKiosk: boolean;
  seoTitle: string | null;
  seoDescription: string | null;
  sameImageForAllLocales: boolean;
  iconMediaId: string | null;
  coverMediaId: string | null;
  createdAt: string;
  updatedAt: string;
  iconMedia?: StoreCategoryMediaPreview | null;
  coverMedia?: StoreCategoryMediaPreview | null;
  parent?: { id: string; name: string; slug: string } | null;
};

export type GlobalStoreMediaPreview = {
  id: string;
  publicUrl: string;
  originalName: string;
  mimeType: string;
};

export type StoreSocialLink = {
  platform: string;
  url: string;
};

export type GlobalStore = {
  id: string;
  name: string;
  normalizedName?: string;
  slug: string;
  slugAutoGenerated?: boolean;
  logoMediaId: string | null;
  description: string | null;
  phone: string | null;
  email: string | null;
  websiteUrl: string | null;
  socialLinksJson: StoreSocialLink[] | Record<string, unknown> | null;
  status: StoreStatus;
  createdBy: string;
  updatedBy: string | null;
  createdAt: string;
  updatedAt: string;
  logoMedia: GlobalStoreMediaPreview | null;
};

export type GlobalStoreListResponse = {
  items: GlobalStore[];
  total: number;
  page: number;
  limit: number;
};

export type MallFloor = {
  id: string;
  tenantId: string;
  mallId: string;
  name: string;
  label: string;
  sortOrder: number;
  active: boolean;
  createdAt: string;
  updatedAt: string;
};

export type MallStore = {
  id: string;
  tenantId: string;
  mallId: string;
  globalStoreId: string;
  categoryId: string | null;
  detailTitle: string | null;
  localDescription: string | null;
  localLogoMediaId: string | null;
  floorId: string | null;
  floor: string | null;
  storeNo: string | null;
  phone: string | null;
  whatsappPhone: string | null;
  email: string | null;
  workingHoursJson: Record<string, unknown> | null;
  locationJson: Record<string, unknown> | null;
  isFeatured: boolean;
  isSoon: boolean;
  searchTags: string[];
  sortOrder: number;
  status: StoreStatus;
  createdBy: string;
  updatedBy: string | null;
  createdAt: string;
  updatedAt: string;
  globalStore: GlobalStore;
  localLogoMedia: GlobalStoreMediaPreview | null;
  floorRecord?: MallFloor | null;
  category?: StoreCategory | null;
};

export type MallStoreListResponse = {
  items: MallStore[];
  total: number;
  page: number;
  limit: number;
};

export function buildStoreCategoryTreeOptions(
  categories: StoreCategory[],
  parentId: string | null = null,
  depth = 0,
): { id: string; label: string; depth: number }[] {
  return categories
    .filter((c) => (c.parentCategoryId ?? null) === parentId)
    .sort((a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name, 'tr'))
    .flatMap((c) => [
      { id: c.id, label: c.name, depth },
      ...buildStoreCategoryTreeOptions(categories, c.id, depth + 1),
    ]);
}

// ─── Store Categories (mall-scoped) ───────────────────────────────────────────

export async function apiStoreCategoriesList(
  token: string,
  tenantId: string,
  mallId: string,
  opts?: { search?: string; activeOnly?: boolean; parentCategoryId?: string },
): Promise<StoreCategory[]> {
  const params = new URLSearchParams();
  if (opts?.search) params.set('search', opts.search);
  if (opts?.activeOnly) params.set('activeOnly', 'true');
  if (opts?.parentCategoryId !== undefined) params.set('parentCategoryId', opts.parentCategoryId);
  const qs = params.toString();
  return request<StoreCategory[]>(`/store-categories${qs ? `?${qs}` : ''}`, {
    method: 'GET',
    token,
    tenantId,
    mallId,
  });
}

export async function apiStoreCategoryGet(
  token: string,
  tenantId: string,
  mallId: string,
  id: string,
): Promise<StoreCategory> {
  return request<StoreCategory>(`/store-categories/${id}`, { method: 'GET', token, tenantId, mallId });
}

export async function apiStoreCategoryCreate(
  token: string,
  tenantId: string,
  mallId: string,
  body: {
    name: string;
    description?: string;
    parentCategoryId?: string | null;
    slug?: string;
    sortOrder?: number;
    active?: boolean;
    color?: string;
    showInWebsite?: boolean;
    showInMobile?: boolean;
    showInKiosk?: boolean;
    seoTitle?: string;
    seoDescription?: string;
    sameImageForAllLocales?: boolean;
    iconMediaId?: string | null;
    coverMediaId?: string | null;
  },
): Promise<StoreCategory> {
  return request<StoreCategory>('/store-categories', {
    method: 'POST',
    token,
    tenantId,
    mallId,
    body: JSON.stringify(body),
  });
}

export async function apiStoreCategoryUpdate(
  token: string,
  tenantId: string,
  mallId: string,
  id: string,
  body: Partial<{
    name: string;
    description: string | null;
    parentCategoryId: string | null;
    slug: string;
    sortOrder: number;
    active: boolean;
    color: string | null;
    showInWebsite: boolean;
    showInMobile: boolean;
    showInKiosk: boolean;
    seoTitle: string | null;
    seoDescription: string | null;
    sameImageForAllLocales: boolean;
    iconMediaId: string | null;
    coverMediaId: string | null;
  }>,
): Promise<StoreCategory> {
  return request<StoreCategory>(`/store-categories/${id}`, {
    method: 'PATCH',
    token,
    tenantId,
    mallId,
    body: JSON.stringify(body),
  });
}

export async function apiStoreCategoriesReorder(
  token: string,
  tenantId: string,
  mallId: string,
  orderedIds: string[],
): Promise<StoreCategory[]> {
  return request<StoreCategory[]>('/store-categories/reorder', {
    method: 'PATCH',
    token,
    tenantId,
    mallId,
    body: JSON.stringify({ orderedIds }),
  });
}

export async function apiStoreCategoryDelete(
  token: string,
  tenantId: string,
  mallId: string,
  id: string,
): Promise<void> {
  return request<void>(`/store-categories/${id}`, { method: 'DELETE', token, tenantId, mallId });
}

// ─── Global Stores ────────────────────────────────────────────────────────────

export async function apiGlobalStoresList(
  token: string,
  tenantId: string,
  opts?: { search?: string; status?: StoreStatus; page?: number; limit?: number },
): Promise<GlobalStoreListResponse> {
  const params = new URLSearchParams();
  if (opts?.search) params.set('search', opts.search);
  if (opts?.status) params.set('status', opts.status);
  if (opts?.page) params.set('page', String(opts.page));
  appendLimitParam(params, opts?.limit);
  const qs = params.toString();
  return request<GlobalStoreListResponse>(`/global-stores${qs ? `?${qs}` : ''}`, {
    method: 'GET',
    token,
    tenantId,
  });
}

export async function apiGlobalStoreGet(token: string, tenantId: string, id: string): Promise<GlobalStore> {
  return request<GlobalStore>(`/global-stores/${id}`, { method: 'GET', token, tenantId });
}

export async function apiGlobalStoreCreate(
  token: string,
  tenantId: string,
  body: {
    name: string;
    slug?: string;
    logoMediaId?: string;
    description?: string;
    phone?: string;
    email?: string;
    websiteUrl?: string;
    socialLinks?: StoreSocialLink[];
    status?: StoreStatus;
  },
): Promise<GlobalStore> {
  return request<GlobalStore>('/global-stores', {
    method: 'POST',
    token,
    tenantId,
    body: JSON.stringify(body),
  });
}

export async function apiGlobalStoreUpdate(
  token: string,
  tenantId: string,
  id: string,
  body: Partial<{
    name: string;
    slug: string;
    logoMediaId: string | null;
    description: string | null;
    phone: string | null;
    email: string | null;
    websiteUrl: string | null;
    socialLinks: StoreSocialLink[] | null;
    status: StoreStatus;
  }>,
): Promise<GlobalStore> {
  return request<GlobalStore>(`/global-stores/${id}`, {
    method: 'PATCH',
    token,
    tenantId,
    body: JSON.stringify(body),
  });
}

export async function apiGlobalStoreDelete(token: string, tenantId: string, id: string): Promise<void> {
  return request<void>(`/global-stores/${id}`, { method: 'DELETE', token, tenantId });
}

// ─── Mall Floors ──────────────────────────────────────────────────────────────

export async function apiMallFloorsList(
  token: string,
  tenantId: string,
  mallId: string,
): Promise<MallFloor[]> {
  return request<MallFloor[]>('/mall-floors', { method: 'GET', token, tenantId, mallId });
}

export async function apiMallFloorCreate(
  token: string,
  tenantId: string,
  mallId: string,
  body: { name: string; label: string; sortOrder?: number; active?: boolean },
): Promise<MallFloor> {
  return request<MallFloor>('/mall-floors', {
    method: 'POST',
    token,
    tenantId,
    mallId,
    body: JSON.stringify(body),
  });
}

export async function apiMallFloorUpdate(
  token: string,
  tenantId: string,
  mallId: string,
  id: string,
  body: Partial<{ name: string; label: string; sortOrder: number; active: boolean }>,
): Promise<MallFloor> {
  return request<MallFloor>(`/mall-floors/${id}`, {
    method: 'PATCH',
    token,
    tenantId,
    mallId,
    body: JSON.stringify(body),
  });
}

export async function apiMallFloorsReorder(
  token: string,
  tenantId: string,
  mallId: string,
  orderedIds: string[],
): Promise<MallFloor[]> {
  return request<MallFloor[]>('/mall-floors/reorder', {
    method: 'PATCH',
    token,
    tenantId,
    mallId,
    body: JSON.stringify({ orderedIds }),
  });
}

export async function apiMallFloorDelete(
  token: string,
  tenantId: string,
  mallId: string,
  id: string,
): Promise<void> {
  return request<void>(`/mall-floors/${id}`, { method: 'DELETE', token, tenantId, mallId });
}

// ─── Mall Stores ──────────────────────────────────────────────────────────────

export async function apiMallStoresList(
  token: string,
  tenantId: string,
  mallId: string,
  opts?: { search?: string; categoryId?: string; status?: StoreStatus; isFeatured?: boolean; page?: number; limit?: number },
): Promise<MallStoreListResponse> {
  const params = new URLSearchParams();
  if (opts?.search) params.set('search', opts.search);
  if (opts?.categoryId) params.set('categoryId', opts.categoryId);
  if (opts?.status) params.set('status', opts.status);
  if (opts?.isFeatured === true || opts?.isFeatured === false) {
    params.set('isFeatured', opts.isFeatured ? 'true' : 'false');
  }
  if (opts?.page) params.set('page', String(opts.page));
  appendLimitParam(params, opts?.limit);
  const qs = params.toString();
  return request<MallStoreListResponse>(`/mall-stores${qs ? `?${qs}` : ''}`, {
    method: 'GET',
    token,
    tenantId,
    mallId,
  });
}

export async function apiMallStoreGet(
  token: string,
  tenantId: string,
  mallId: string,
  id: string,
): Promise<MallStore> {
  return request<MallStore>(`/mall-stores/${id}`, { method: 'GET', token, tenantId, mallId });
}

export async function apiMallStoreAssign(
  token: string,
  tenantId: string,
  mallId: string,
  body: {
    globalStoreId: string;
    categoryId?: string | null;
    detailTitle?: string;
    localDescription?: string;
    floorId?: string;
    floor?: string;
    storeNo?: string;
    phone?: string;
    whatsappPhone?: string;
    workingHoursJson?: Record<string, unknown>;
    locationJson?: Record<string, unknown>;
    isFeatured?: boolean;
    isSoon?: boolean;
    searchTags?: string[];
    sortOrder?: number;
    status?: StoreStatus;
  },
): Promise<MallStore> {
  return request<MallStore>('/mall-stores/assign', {
    method: 'POST',
    token,
    tenantId,
    mallId,
    body: JSON.stringify(body),
  });
}

export async function apiMallStoreUpdate(
  token: string,
  tenantId: string,
  mallId: string,
  id: string,
  body: Partial<{
    detailTitle: string | null;
    localDescription: string | null;
    categoryId: string | null;
    floorId: string | null;
    floor: string | null;
    storeNo: string | null;
    phone: string | null;
    whatsappPhone: string | null;
    workingHoursJson: Record<string, unknown> | null;
    locationJson: Record<string, unknown> | null;
    isFeatured: boolean;
    isSoon?: boolean;
    searchTags?: string[];
    sortOrder: number;
    status: StoreStatus;
  }>,
): Promise<MallStore> {
  return request<MallStore>(`/mall-stores/${id}`, {
    method: 'PATCH',
    token,
    tenantId,
    mallId,
    body: JSON.stringify(body),
  });
}

export async function apiMallStoreDelete(
  token: string,
  tenantId: string,
  mallId: string,
  id: string,
): Promise<void> {
  return request<void>(`/mall-stores/${id}`, { method: 'DELETE', token, tenantId, mallId });
}

export async function apiMallStoreFeature(
  token: string,
  tenantId: string,
  mallId: string,
  id: string,
): Promise<MallStore> {
  return request<MallStore>(`/mall-stores/${id}/feature`, { method: 'POST', token, tenantId, mallId });
}

export async function apiMallStoreUnfeature(
  token: string,
  tenantId: string,
  mallId: string,
  id: string,
): Promise<MallStore> {
  return request<MallStore>(`/mall-stores/${id}/unfeature`, { method: 'POST', token, tenantId, mallId });
}
